// 保留字
export const savedWords = [
  'abstract',
  'arguments',
  'boolean',
  'break',
  'byte',
  'case',
  'catch',
  'char',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'double',
  'else',
  'enum',
  'eval',
  'export',
  'extends',
  'false',
  'final',
  'finally',
  'float',
  'for',
  'function',
  'goto',
  'if',
  'implements',
  'import',
  'in',
  'instanceof',
  'int',
  'interface',
  'let',
  'long',
  'native',
  'new',
  'null',
  'package',
  'private',
  'protected',
  'public',
  'return',
  'short',
  'static',
  'super',
  'switch',
  'synchronized',
  'this',
  'throw',
  'throws',
  'transient',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'volatile',
  'while',
  'with',
  'yield'
]

export const declareSaveWord = ['arguments', 'boolean', 'char', 'class', 'const', 'enum', 'function', 'implements', 'import', 'interface', 'let', 'long', 'native', 'new', 'var', 'with', 'yield']

export const attributeSaveWord = ['abstract', 'default', 'double', 'false', 'float', 'int', 'null', 'package', 'private', 'protected', 'public', 'short', 'static', 'this', 'true', 'void', 'volatile']

export const controlSaveWord = ['break', 'byte', 'case', 'catch', 'continue', 'debugger', 'delete', 'do', 'else', 'eval', 'export', 'extends', 'final', 'finally', 'for', 'goto', 'if', 'in', 'instanceof', 'return', 'super', 'switch', 'synchronized', 'throw', 'throws', 'transient', 'try', 'typeof', 'while']
